const { z } = require("zod");
const { isMinMaxLoanAmountRangeValid, isMinMaxTermRangeValid } = require("../../../utils/lender/validateLenderProductRanges");

// subtype support (same as create)
const nestedTypeSchema = z.record(
  z.string(),
  z.array(z.string())
);

// allow number OR string → convert to string
const experienceSchema = z
  .union([z.number().int(), z.string()])
  .optional()
  .transform((val) => {
    if (val === undefined || val === null) return undefined;
    return String(val);
  });

const businessTypeSchema = z.object({
  name: z.string(),
  subTypes: z.array(z.string()).optional(),
});

const propertyTypeSchema = z.object({
  type: z.string(),
  subTypes: z.array(z.string()).optional(),
});

const groupedBusinessTypesSchema = z
  .union([nestedTypeSchema, z.array(businessTypeSchema)])
  .optional();

const groupedPropertyTypesSchema = z
  .union([nestedTypeSchema, z.array(propertyTypeSchema)])
  .optional();

const updateLenderLoanProductSchema = z
  .object({
    // 💰 FINANCIAL
    minLoanAmount: z.number().positive().optional(),
    maxLoanAmount: z.number().positive().optional(),

    minTermMonths: z.number().int().positive().optional(),
    maxTermMonths: z.number().int().positive().optional(),

    // ✅ LTV
maxLtvPercent: z.number().min(0).optional(),
    minMezzLtvPercent: z.number().min(0).optional(),
    maxMezzLtvPercent: z.number().min(0).optional(),
    exitFeePercent: z.number().min(0).optional(),
    preferredReturnPercent: z.number().min(0).optional(),
maxArvPercent: z.number().min(0).optional(),
    maxLtcPercent: z.number().min(0).optional(),

    minCreditScore: z.number().int().optional(),

    // ✅ FIXED
    minExperience: experienceSchema,

    interestRateRange: z.string().optional(),

    originationPointsPercent: z.number().min(0).optional(),
    extensionAvailable: z.boolean().optional(),
    personalGuaranteeRequired: z.boolean().optional(),
    firstTimeBorrowersAllowed: z.boolean().optional(),
    minDscr: z.number().positive().optional(),
    minDebtYieldPercent: z.number().min(0).optional(),
    amortizationYears: z.number().int().positive().optional(),
    minUnits: z.number().int().positive().optional(),
    prepaymentStructure: z.string().optional(),
    minPropertiesInPortfolio: z.number().int().positive().optional(),
    maxPropertiesInPortfolio: z.number().int().positive().optional(),
    interestOnlyAvailable: z.boolean().optional(),
    shortTermRentalsOk: z.boolean().optional(),
    foreignNationalsAllowed: z.boolean().optional(),
    gcRequired: z.boolean().optional(),
    completionGuaranteeRequired: z.boolean().optional(),
    preferredLenderPlp: z.boolean().optional(),
    maxRateSpreadPercent: z.number().min(0).optional(),
    minRateSpreadPercent: z.number().min(0).optional(),
    sbaGuaranteePercent: z.number().min(0).max(100).optional(),
    minAnnualRevenue: z.number().positive().optional(),
    maxFinancingPercent: z.number().min(0).max(100).optional(),
    useOfFunds: z.string().optional(),
    collateralRequirements: z.string().optional(),
    rateStructure: z.string().optional(),
    refinanceAllowed: z.boolean().optional(),
    workingCapitalEligible: z.boolean().optional(),
    lifeInsuranceMayBeRequired: z.boolean().optional(),
    startupAllowed: z.boolean().optional(),
    environmentalReportRequired: z.boolean().optional(),
    appraisalRequired: z.boolean().optional(),
    avgTurnaroundDays: z.number().int().positive().optional(),
    requiredInjectionPercent: z.number().min(0).max(100).optional(),
    goodwillFinancingAllowed: z.boolean().optional(),
    sellerFinancingAllowed: z.boolean().optional(),
    preferredDscr: z.number().positive().optional(),
    maxTermRealEstateMonths: z.number().int().positive().optional(),
    maxTermWorkingCapitalMonths: z.number().int().positive().optional(),
    intangibleAssetsAllowed: z.boolean().optional(),
    equipmentIncluded: z.boolean().optional(),
    realEstateIncluded: z.boolean().optional(),
    franchiseAcquisitionAllowed: z.boolean().optional(),
    collateralRequired: z.boolean().optional(),
    collateralAsDownPaymentAllowed: z.boolean().optional(),
    maxTermEquipmentMonths: z.number().int().positive().optional(),
    maximumDebtService: z.number().positive().optional(),
    businessAcquisitionAllowed: z.boolean().optional(),
    equipmentPurchaseAllowed: z.boolean().optional(),
    businessCreditRequired: z.boolean().optional(),
    usOperatingBusinessRequired: z.boolean().optional(),
    startupEligible: z.boolean().optional(),
    franchiseEligible: z.boolean().optional(),
    foreignOwnershipAllowed: z.boolean().optional(),
    bankruptcyAllowed: z.boolean().optional(),
    prepaymentPenalty: z.boolean().optional(),
    minLiquidityRequirement: z.string().optional(),
    ownerOccupancyRequirement: z.string().optional(),
    minTimeInBusinessMonths: z.number().int().min(0).optional(),
    lineOfCreditAvailable: z.boolean().optional(),
    seasonalWorkingCapitalAllowed: z.boolean().optional(),
    accountsReceivableFinancingAllowed: z.boolean().optional(),
    usedEquipmentAllowed: z.boolean().optional(),
    leaseholdImprovementsAllowed: z.boolean().optional(),
    existingBusinessAllowed: z.boolean().optional(),
    ownerOccupiedRequired: z.boolean().optional(),
    maxTotalProjectAmount: z.number().positive().optional(),
    maxSba504DebentureAmount: z.number().positive().optional(),
    jobCreationRequired: z.boolean().optional(),
    maxUsdaGuaranteeAmount: z.number().positive().optional(),
    usdaGuaranteePercent: z.number().min(0).max(100).optional(),
    ruralAreaRequired: z.boolean().optional(),
    constructionAllowed: z.boolean().optional(),
    energyEfficiencyImprovementsAllowed: z.boolean().optional(),
    renewableEnergyImprovementsAllowed: z.boolean().optional(),
    waterEfficiencyImprovementsAllowed: z.boolean().optional(),
    resiliencyImprovementsAllowed: z.boolean().optional(),
    seismicImprovementsAllowed: z.boolean().optional(),
    hvacBuildingSystemsAllowed: z.boolean().optional(),
    solarRenewableEnergyAllowed: z.boolean().optional(),
    roofImprovementsAllowed: z.boolean().optional(),
    lightingImprovementsAllowed: z.boolean().optional(),
    buildingEnvelopeAllowed: z.boolean().optional(),
    propertyOwnerConsentRequired: z.boolean().optional(),
    seniorLenderConsentRequired: z.boolean().optional(),
    mortgageLenderConsentRequired: z.boolean().optional(),
    energyAuditRequired: z.boolean().optional(),
    cPaceEligibleJurisdictions: z.string().optional(),
    advanceRatePercent: z.number().min(0).max(100).optional(),
    transactionFeePercent: z.number().min(0).max(100).optional(),
    minGrossMarginPercent: z.number().min(0).max(100).optional(),
    internationalPosAllowed: z.boolean().optional(),
    saleLeasebackAvailable: z.boolean().optional(),
    discountFeePercent: z.number().min(0).max(100).optional(),
    maxInvoiceAgeDays: z.number().int().positive().optional(),
    nonRecourseAvailable: z.boolean().optional(),
    governmentInvoicesOk: z.boolean().optional(),
    earlyPaymentDiscountPercent: z.number().min(0).max(100).optional(),
    paymentTermsExtensionDays: z.number().int().positive().optional(),
    dynamicDiscountingAvailable: z.boolean().optional(),
    reverseFactoringAvailable: z.boolean().optional(),
    minPropertyValueAmount: z.number().min(0).optional(),
    maxPropertyValueAmount: z.number().min(0).optional(),
    unit1Allowed: z.boolean().optional(),
    unit2Allowed: z.boolean().optional(),
    unit3Allowed: z.boolean().optional(),
    unit4Allowed: z.boolean().optional(),
    ownerOccupiedAllowed: z.boolean().optional(),
    nonOwnerOccupiedAllowed: z.boolean().optional(),
    investmentPropertyAllowed: z.boolean().optional(),
    commercialRealEstateAllowed: z.boolean().optional(),
    purchaseAllowed: z.boolean().optional(),
    cashOutRefinanceAllowed: z.boolean().optional(),
    renovationAllowed: z.boolean().optional(),
    heavyRehabAllowed: z.boolean().optional(),
    lightRehabAllowed: z.boolean().optional(),
    vacantPropertyAllowed: z.boolean().optional(),
    tenantOccupiedAllowed: z.boolean().optional(),
    foreclosureReoAllowed: z.boolean().optional(),
    llcEntityBorrowerAllowed: z.boolean().optional(),
    propertyTypesExcluded: z.string().optional(),
    maxLtvCashOutPercent: z.number().min(0).optional(),
    minRentalIncomeAmount: z.number().min(0).optional(),
    rentalIncomeRequired: z.boolean().optional(),
    longTermRentalAllowed: z.boolean().optional(),
    leaseRequired: z.boolean().optional(),
    marketRentScheduleAccepted: z.boolean().optional(),
    firstTimeInvestorAllowed: z.boolean().optional(),
    foreclosureShortSaleAllowed: z.boolean().optional(),
    minInvestorExperienceDeals: z.number().int().min(0).optional(),
    moderateRehabAllowed: z.boolean().optional(),
    groundUpConstructionAllowed: z.boolean().optional(),
    shortSaleAllowed: z.boolean().optional(),
    borrowerExperienceRequired: z.boolean().optional(),
    rehabFundsFinanced: z.boolean().optional(),
    rehabFundsMaxPercent: z.number().min(0).optional(),
    drawScheduleRequired: z.boolean().optional(),
    minConstructionProjectsCompleted: z.number().int().min(0).optional(),
    tearDownRebuildAllowed: z.boolean().optional(),
    majorRenovationAllowed: z.boolean().optional(),
    constructionToPermanentAllowed: z.boolean().optional(),
    lotPurchaseIncluded: z.boolean().optional(),
    landAlreadyOwnedAllowed: z.boolean().optional(),
    landEquityAllowed: z.boolean().optional(),
    softCostsFinanced: z.boolean().optional(),
    hardCostsFinanced: z.boolean().optional(),
    contingencyFinanced: z.boolean().optional(),
    interestReserveFinanced: z.boolean().optional(),
    ownerBuilderAllowed: z.boolean().optional(),
    firstTimeBuilderAllowed: z.boolean().optional(),
    inspectionRequiredForDraws: z.boolean().optional(),
    amortizationMonths: z.number().int().min(0).optional(),
    minOwnershipExperienceYears: z.number().int().min(0).optional(),
    rateTermRefinanceAllowed: z.boolean().optional(),
    multifamily5PlusAllowed: z.boolean().optional(),
    apartmentAllowed: z.boolean().optional(),
    officeAllowed: z.boolean().optional(),
    retailAllowed: z.boolean().optional(),
    industrialAllowed: z.boolean().optional(),
    mixedUseAllowed: z.boolean().optional(),
    selfStorageAllowed: z.boolean().optional(),
    hotelHospitalityAllowed: z.boolean().optional(),
    medicalHealthcareAllowed: z.boolean().optional(),
    studentHousingAllowed: z.boolean().optional(),
    mobileHomeParkAllowed: z.boolean().optional(),
    seniorHousingAllowed: z.boolean().optional(),
    minOccupancyPercent: z.number().min(0).optional(),
    minAnnualNoiAmount: z.number().min(0).optional(),
    maxUnits: z.number().int().min(0).optional(),
    stabilizedPropertyRequired: z.boolean().optional(),
    leaseUpPropertiesAccepted: z.boolean().optional(),
    valueAddPropertiesAccepted: z.boolean().optional(),
    newlyRenovatedPropertiesAllowed: z.boolean().optional(),
    propertyConditionAssessmentRequired: z.boolean().optional(),
    agencyProgram: z.string().optional(),
    supplementalFinancingAllowed: z.boolean().optional(),
    marketRateMultifamilyAllowed: z.boolean().optional(),
    affordableHousingAllowed: z.boolean().optional(),
    cooperativeHousingAllowed: z.boolean().optional(),
    manufacturedHousingCommunityAllowed: z.boolean().optional(),
    smallBalanceMultifamilyAllowed: z.boolean().optional(),
    minDscrFixedRate: z.number().min(0).optional(),
    minDscrArm: z.number().min(0).optional(),
    newConstructionAllowed: z.boolean().optional(),
    renovationModerateRehabAllowed: z.boolean().optional(),
    mezzPreferredFinancingType: z.string().optional(),
    acquisitionFinancingAllowed: z.boolean().optional(),
    constructionFinancingAllowed: z.boolean().optional(),
    bridgeFinancingAllowed: z.boolean().optional(),
    valueAddFinancingAllowed: z.boolean().optional(),
    recapitalizationAllowed: z.boolean().optional(),
    equityGapFinancingAllowed: z.boolean().optional(),
    maxStabilizedLtvPercent: z.number().min(0).optional(),
    debtRefinanceAllowed: z.boolean().optional(),
    minLoanSizeForPropertyTypeAmount: z.number().min(0).optional(),
    badBoyGuaranteeRequired: z.boolean().optional(),
    springingRecourseAllowed: z.boolean().optional(),
    defeasanceAllowed: z.boolean().optional(),
    yieldMaintenanceAllowed: z.boolean().optional(),
    interestOnlyPeriodMonths: z.number().int().min(0).optional(),
    portfolioRefinanceAllowed: z.boolean().optional(),
    crossCollateralizationAllowed: z.boolean().optional(),
    residential1To4Allowed: z.boolean().optional(),
    minPortfolioValueAmount: z.number().min(0).optional(),
    maxPortfolioValueAmount: z.number().min(0).optional(),
    minPortfolioNoiAmount: z.number().min(0).optional(),
    minPortfolioRentalIncomeAmount: z.number().min(0).optional(),
    minCashReservesAmount: z.number().min(0).optional(),
    minMonthsReserves: z.number().int().min(0).optional(),
    minEbitdaAmount: z.number().min(0).optional(),
    newEquipmentAllowed: z.boolean().optional(),
    equipmentRefinanceAllowed: z.boolean().optional(),
    equipmentLeaseAllowed: z.boolean().optional(),
    leaseToOwnAllowed: z.boolean().optional(),
    installationCostsFinanced: z.boolean().optional(),
    transportationFreightCostsFinanced: z.boolean().optional(),
    firstTimeBusinessOwnersAllowed: z.boolean().optional(),
    minEquipmentValueAmount: z.number().min(0).optional(),
    maxEquipmentValueAmount: z.number().min(0).optional(),
    maxEquipmentAgeYears: z.number().int().min(0).optional(),
    minUsefulLifeRemainingYears: z.number().int().min(0).optional(),
    equipmentAppraisalRequired: z.boolean().optional(),
    vendorInvoiceRequired: z.boolean().optional(),
    equipmentTypesExcluded: z.string().optional(),
    industriesExcluded: z.string().optional(),
    maxAdvanceRatePercent: z.number().min(0).optional(),
    minMonthlyArAmount: z.number().min(0).optional(),
    recourseFactoringAllowed: z.boolean().optional(),
    invoiceFactoringAllowed: z.boolean().optional(),
    arLineOfCreditAllowed: z.boolean().optional(),
    assetBasedLendingAllowed: z.boolean().optional(),
    purchaseOrderFinancingAllowed: z.boolean().optional(),
    domesticArAllowed: z.boolean().optional(),
    internationalArAllowed: z.boolean().optional(),
    b2bReceivablesAllowed: z.boolean().optional(),
    b2cReceivablesAllowed: z.boolean().optional(),
    concentrationLimitPercent: z.number().min(0).optional(),
    minInvoiceSizeAmount: z.number().min(0).optional(),
    maxInvoiceSizeAmount: z.number().min(0).optional(),
    minInvoiceAgeDays: z.number().int().min(0).optional(),
    maxInvoiceDilutionPercent: z.number().min(0).optional(),
    minDebtorCreditScore: z.number().int().min(0).optional(),
    customerCreditInsuranceRequired: z.boolean().optional(),
    existingLiensAccepted: z.boolean().optional(),
    taxLiensAccepted: z.boolean().optional(),
    uccFilingRequired: z.boolean().optional(),
    minEligibleArAmount: z.number().min(0).optional(),
    maxArConcentrationPercent: z.number().min(0).optional(),
    minMonthlyPayablesAmount: z.number().min(0).optional(),
    vendorSupplierFinancingAllowed: z.boolean().optional(),
    tradePayablesFinancingAllowed: z.boolean().optional(),
    inventoryFinancingAllowed: z.boolean().optional(),
    supplyChainFinanceAllowed: z.boolean().optional(),
    domesticVendorsAllowed: z.boolean().optional(),
    internationalVendorsAllowed: z.boolean().optional(),
    governmentContractorsAllowed: z.boolean().optional(),
    maxVendorConcentrationPercent: z.number().min(0).optional(),
    minVendorCreditQuality: z.string().optional(),
    vendorVerificationRequired: z.boolean().optional(),
    purchaseOrderRequired: z.boolean().optional(),
    minEligiblePayablesAmount: z.number().min(0).optional(),
    maxPayablesConcentrationPercent: z.number().min(0).optional(),
    domesticPosAllowed: z.boolean().optional(),
    governmentPosAllowed: z.boolean().optional(),
    recurringPosAllowed: z.boolean().optional(),
    oneTimePosAllowed: z.boolean().optional(),
    manufacturingRequired: z.boolean().optional(),
    finishedGoodsAllowed: z.boolean().optional(),
    rawMaterialsAllowed: z.boolean().optional(),
    supplierVendorPaymentAllowed: z.boolean().optional(),
    purchaseOrderAssignmentAllowed: z.boolean().optional(),
    minPoAmountAmount: z.number().min(0).optional(),
    maxPoAmountAmount: z.number().min(0).optional(),
    minCustomerCreditScore: z.number().int().min(0).optional(),
    minCustomerCreditRating: z.string().optional(),
    maxCustomerConcentrationPercent: z.number().min(0).optional(),
    minGrossProfitMarginPercent: z.number().min(0).optional(),
    minCustomerDepositPercent: z.number().min(0).optional(),
    customerVerificationRequired: z.boolean().optional(),
    minEligiblePoValueAmount: z.number().min(0).optional(),
    maxPoConcentrationPercent: z.number().min(0).optional(),
    criteriaNotes: z.string().optional(),

    // ✅ JSON (subtype support — record or array)
    businessTypes: groupedBusinessTypesSchema,
    propertyTypes: groupedPropertyTypesSchema,

    // ✅ ARRAY → converted to CSV in API
    statesSupported: z.array(z.string()).optional(),

    // ✅ EQUIPMENT
    equipmentTypes: z.array(z.string()).optional(),
    otherEquipmentExplanation: z.string().optional(),

    // ✅ STATUS
    isActive: z.boolean().optional(),
  })

  // ✅ at least one field
  .refine((data) => Object.keys(data).length > 0, {
    message: "At least one field must be provided for update",
  })

  // ✅ loan validation
  .refine(
    (data) => isMinMaxLoanAmountRangeValid(data),
    {
      message: "minLoanAmount cannot be greater than maxLoanAmount",
    },
  )

  // ✅ term validation
  .refine(
    (data) => isMinMaxTermRangeValid(data),
    {
      message: "minTermMonths cannot be greater than maxTermMonths",
    },
  );

module.exports = {
  updateLenderLoanProductSchema,
};