const { z } = require("zod");
const {
  loanProductCodeSchema,
} = require("../../shared/loanProductCodeSchema");

const loanProductEnum = loanProductCodeSchema;
const decimalField = z.union([z.string(), z.number()]).optional();
const numberField = z.union([z.string(), z.number()]).optional();

const businessTypeSchema = z.object({
  name: z.string(),
  subTypes: z.array(z.string()).optional(),
});

const propertyTypeSchema = z.object({
  type: z.string(),
  subTypes: z.array(z.string()).optional(),
});

const lenderProductPayloadSchema = z
  .object({
    id: z.string().uuid().optional(),
    loanProductCode: loanProductEnum.optional(),

    businessTypes: z.array(businessTypeSchema).optional(),
    propertyTypes: z.array(propertyTypeSchema).optional(),

    equipmentTypes: z.array(z.string()).optional(),
    otherEquipmentExplanation: z.string().optional(),

    minLoanAmount: decimalField,
    maxLoanAmount: decimalField,

    minTermMonths: z.number().int().nonnegative().optional(),
    maxTermMonths: z.number().int().nonnegative().optional(),

    maxLtvPercent: decimalField,
    minMezzLtvPercent: decimalField,
    maxMezzLtvPercent: decimalField,
    exitFeePercent: decimalField,
    preferredReturnPercent: decimalField,
    maxArvPercent: decimalField,
    maxLtcPercent: decimalField,

    minCreditScore: z.number().int().nonnegative().optional(),
    minExperience: z.union([z.string(), z.number()]).optional(),

    interestRateRange: z.string().optional(),
    originationPointsPercent: numberField,
    extensionAvailable: z.boolean().optional(),
    personalGuaranteeRequired: z.boolean().optional(),
    firstTimeBorrowersAllowed: z.boolean().optional(),
    minDscr: numberField,
    minDebtYieldPercent: numberField,
    amortizationYears: z.number().int().optional(),
    minUnits: z.number().int().optional(),
    prepaymentStructure: z.string().optional(),
    minPropertiesInPortfolio: z.number().int().optional(),
    maxPropertiesInPortfolio: z.number().int().optional(),
    interestOnlyAvailable: z.boolean().optional(),
    shortTermRentalsOk: z.boolean().optional(),
    foreignNationalsAllowed: z.boolean().optional(),
    preferredLenderPlp: z.boolean().optional(),
    maxRateSpreadPercent: numberField,
    minRateSpreadPercent: numberField,
    sbaGuaranteePercent: numberField,
    minAnnualRevenue: decimalField,
    maxFinancingPercent: numberField,
    useOfFunds: z.string().optional(),
    collateralRequirements: z.string().optional(),
    rateStructure: z.string().optional(),
    refinanceAllowed: z.boolean().optional(),
    workingCapitalEligible: z.boolean().optional(),
    lifeInsuranceMayBeRequired: z.boolean().optional(),
    startupAllowed: z.boolean().optional(),
    environmentalReportRequired: z.boolean().optional(),
    appraisalRequired: z.boolean().optional(),
    avgTurnaroundDays: z.number().int().optional(),
    requiredInjectionPercent: numberField,
    goodwillFinancingAllowed: z.boolean().optional(),
    sellerFinancingAllowed: z.boolean().optional(),
    preferredDscr: numberField,
    maxTermRealEstateMonths: z.number().int().optional(),
    maxTermWorkingCapitalMonths: z.number().int().optional(),
    intangibleAssetsAllowed: z.boolean().optional(),
    equipmentIncluded: z.boolean().optional(),
    realEstateIncluded: z.boolean().optional(),
    franchiseAcquisitionAllowed: z.boolean().optional(),
    collateralRequired: z.boolean().optional(),
    collateralAsDownPaymentAllowed: z.boolean().optional(),
    maxTermEquipmentMonths: z.number().int().optional(),
    maximumDebtService: numberField,
    businessAcquisitionAllowed: z.boolean().optional(),
    equipmentPurchaseAllowed: z.boolean().optional(),
    businessCreditRequired: z.boolean().optional(),
    usOperatingBusinessRequired: z.boolean().optional(),
    startupEligible: z.boolean().optional(),
    franchiseEligible: z.boolean().optional(),
    foreignOwnershipAllowed: z.boolean().optional(),
    bankruptcyAllowed: z.boolean().optional(),
    prepaymentPenalty: z.boolean().optional(),
    minLiquidityRequirement: z.string().optional(),
    ownerOccupancyRequirement: z.string().optional(),
    minTimeInBusinessMonths: z.number().int().optional(),
    lineOfCreditAvailable: z.boolean().optional(),
    seasonalWorkingCapitalAllowed: z.boolean().optional(),
    accountsReceivableFinancingAllowed: z.boolean().optional(),
    usedEquipmentAllowed: z.boolean().optional(),
    leaseholdImprovementsAllowed: z.boolean().optional(),
    existingBusinessAllowed: z.boolean().optional(),
    ownerOccupiedRequired: z.boolean().optional(),
    maxTotalProjectAmount: numberField,
    maxSba504DebentureAmount: numberField,
    jobCreationRequired: z.boolean().optional(),
    maxUsdaGuaranteeAmount: numberField,
    usdaGuaranteePercent: numberField,
    ruralAreaRequired: z.boolean().optional(),
    constructionAllowed: z.boolean().optional(),
    energyEfficiencyImprovementsAllowed: z.boolean().optional(),
    renewableEnergyImprovementsAllowed: z.boolean().optional(),
    waterEfficiencyImprovementsAllowed: z.boolean().optional(),
    resiliencyImprovementsAllowed: z.boolean().optional(),
    seismicImprovementsAllowed: z.boolean().optional(),
    hvacBuildingSystemsAllowed: z.boolean().optional(),
    solarRenewableEnergyAllowed: z.boolean().optional(),
    roofImprovementsAllowed: z.boolean().optional(),
    lightingImprovementsAllowed: z.boolean().optional(),
    buildingEnvelopeAllowed: z.boolean().optional(),
    propertyOwnerConsentRequired: z.boolean().optional(),
    seniorLenderConsentRequired: z.boolean().optional(),
    mortgageLenderConsentRequired: z.boolean().optional(),
    energyAuditRequired: z.boolean().optional(),
    cPaceEligibleJurisdictions: z.string().optional(),
    advanceRatePercent: numberField,
    transactionFeePercent: numberField,
    minGrossMarginPercent: numberField,
    internationalPosAllowed: z.boolean().optional(),
    saleLeasebackAvailable: z.boolean().optional(),
    discountFeePercent: numberField,
    maxInvoiceAgeDays: z.number().int().optional(),
    nonRecourseAvailable: z.boolean().optional(),
    governmentInvoicesOk: z.boolean().optional(),
    earlyPaymentDiscountPercent: numberField,
    paymentTermsExtensionDays: z.number().int().optional(),
    dynamicDiscountingAvailable: z.boolean().optional(),
    reverseFactoringAvailable: z.boolean().optional(),
    minPropertyValueAmount: decimalField,
    maxPropertyValueAmount: decimalField,
    unit1Allowed: z.boolean().optional(),
    unit2Allowed: z.boolean().optional(),
    unit3Allowed: z.boolean().optional(),
    unit4Allowed: z.boolean().optional(),
    ownerOccupiedAllowed: z.boolean().optional(),
    nonOwnerOccupiedAllowed: z.boolean().optional(),
    investmentPropertyAllowed: z.boolean().optional(),
    commercialRealEstateAllowed: z.boolean().optional(),
    purchaseAllowed: z.boolean().optional(),
    cashOutRefinanceAllowed: z.boolean().optional(),
    renovationAllowed: z.boolean().optional(),
    heavyRehabAllowed: z.boolean().optional(),
    lightRehabAllowed: z.boolean().optional(),
    vacantPropertyAllowed: z.boolean().optional(),
    tenantOccupiedAllowed: z.boolean().optional(),
    foreclosureReoAllowed: z.boolean().optional(),
    llcEntityBorrowerAllowed: z.boolean().optional(),
    propertyTypesExcluded: z.string().optional(),
    maxLtvCashOutPercent: decimalField,
    minRentalIncomeAmount: decimalField,
    rentalIncomeRequired: z.boolean().optional(),
    longTermRentalAllowed: z.boolean().optional(),
    leaseRequired: z.boolean().optional(),
    marketRentScheduleAccepted: z.boolean().optional(),
    firstTimeInvestorAllowed: z.boolean().optional(),
    foreclosureShortSaleAllowed: z.boolean().optional(),
    minInvestorExperienceDeals: z.number().int().min(0).optional(),
    moderateRehabAllowed: z.boolean().optional(),
    groundUpConstructionAllowed: z.boolean().optional(),
    shortSaleAllowed: z.boolean().optional(),
    borrowerExperienceRequired: z.boolean().optional(),
    rehabFundsFinanced: z.boolean().optional(),
    rehabFundsMaxPercent: decimalField,
    drawScheduleRequired: z.boolean().optional(),
    gcRequired: z.boolean().optional(),
    completionGuaranteeRequired: z.boolean().optional(),
    minConstructionProjectsCompleted: z.number().int().min(0).optional(),
    tearDownRebuildAllowed: z.boolean().optional(),
    majorRenovationAllowed: z.boolean().optional(),
    constructionToPermanentAllowed: z.boolean().optional(),
    lotPurchaseIncluded: z.boolean().optional(),
    landAlreadyOwnedAllowed: z.boolean().optional(),
    landEquityAllowed: z.boolean().optional(),
    softCostsFinanced: z.boolean().optional(),
    hardCostsFinanced: z.boolean().optional(),
    contingencyFinanced: z.boolean().optional(),
    interestReserveFinanced: z.boolean().optional(),
    ownerBuilderAllowed: z.boolean().optional(),
    firstTimeBuilderAllowed: z.boolean().optional(),
    inspectionRequiredForDraws: z.boolean().optional(),
    amortizationMonths: z.number().int().optional(),
    minOwnershipExperienceYears: z.number().int().optional(),
    rateTermRefinanceAllowed: z.boolean().optional(),
    multifamily5PlusAllowed: z.boolean().optional(),
    apartmentAllowed: z.boolean().optional(),
    officeAllowed: z.boolean().optional(),
    retailAllowed: z.boolean().optional(),
    industrialAllowed: z.boolean().optional(),
    mixedUseAllowed: z.boolean().optional(),
    selfStorageAllowed: z.boolean().optional(),
    hotelHospitalityAllowed: z.boolean().optional(),
    medicalHealthcareAllowed: z.boolean().optional(),
    studentHousingAllowed: z.boolean().optional(),
    mobileHomeParkAllowed: z.boolean().optional(),
    seniorHousingAllowed: z.boolean().optional(),
    minOccupancyPercent: decimalField,
    minAnnualNoiAmount: decimalField,
    maxUnits: z.number().int().optional(),
    stabilizedPropertyRequired: z.boolean().optional(),
    leaseUpPropertiesAccepted: z.boolean().optional(),
    valueAddPropertiesAccepted: z.boolean().optional(),
    newlyRenovatedPropertiesAllowed: z.boolean().optional(),
    propertyConditionAssessmentRequired: z.boolean().optional(),
    agencyProgram: z.string().optional(),
    supplementalFinancingAllowed: z.boolean().optional(),
    marketRateMultifamilyAllowed: z.boolean().optional(),
    affordableHousingAllowed: z.boolean().optional(),
    cooperativeHousingAllowed: z.boolean().optional(),
    manufacturedHousingCommunityAllowed: z.boolean().optional(),
    smallBalanceMultifamilyAllowed: z.boolean().optional(),
    minDscrFixedRate: decimalField,
    minDscrArm: decimalField,
    newConstructionAllowed: z.boolean().optional(),
    renovationModerateRehabAllowed: z.boolean().optional(),
    mezzPreferredFinancingType: z.string().optional(),
    acquisitionFinancingAllowed: z.boolean().optional(),
    constructionFinancingAllowed: z.boolean().optional(),
    bridgeFinancingAllowed: z.boolean().optional(),
    valueAddFinancingAllowed: z.boolean().optional(),
    recapitalizationAllowed: z.boolean().optional(),
    equityGapFinancingAllowed: z.boolean().optional(),
    maxStabilizedLtvPercent: decimalField,
    debtRefinanceAllowed: z.boolean().optional(),
    minLoanSizeForPropertyTypeAmount: decimalField,
    badBoyGuaranteeRequired: z.boolean().optional(),
    springingRecourseAllowed: z.boolean().optional(),
    defeasanceAllowed: z.boolean().optional(),
    yieldMaintenanceAllowed: z.boolean().optional(),
    interestOnlyPeriodMonths: z.number().int().optional(),
    portfolioRefinanceAllowed: z.boolean().optional(),
    crossCollateralizationAllowed: z.boolean().optional(),
    residential1To4Allowed: z.boolean().optional(),
    minPortfolioValueAmount: decimalField,
    maxPortfolioValueAmount: decimalField,
    minPortfolioNoiAmount: decimalField,
    minPortfolioRentalIncomeAmount: decimalField,
    minCashReservesAmount: decimalField,
    minMonthsReserves: z.number().int().optional(),
    minEbitdaAmount: decimalField,
    newEquipmentAllowed: z.boolean().optional(),
    equipmentRefinanceAllowed: z.boolean().optional(),
    equipmentLeaseAllowed: z.boolean().optional(),
    leaseToOwnAllowed: z.boolean().optional(),
    installationCostsFinanced: z.boolean().optional(),
    transportationFreightCostsFinanced: z.boolean().optional(),
    firstTimeBusinessOwnersAllowed: z.boolean().optional(),
    minEquipmentValueAmount: decimalField,
    maxEquipmentValueAmount: decimalField,
    maxEquipmentAgeYears: z.number().int().optional(),
    minUsefulLifeRemainingYears: z.number().int().optional(),
    equipmentAppraisalRequired: z.boolean().optional(),
    vendorInvoiceRequired: z.boolean().optional(),
    equipmentTypesExcluded: z.string().optional(),
    industriesExcluded: z.string().optional(),
    maxAdvanceRatePercent: decimalField,
    minMonthlyArAmount: decimalField,
    recourseFactoringAllowed: z.boolean().optional(),
    invoiceFactoringAllowed: z.boolean().optional(),
    arLineOfCreditAllowed: z.boolean().optional(),
    assetBasedLendingAllowed: z.boolean().optional(),
    purchaseOrderFinancingAllowed: z.boolean().optional(),
    domesticArAllowed: z.boolean().optional(),
    internationalArAllowed: z.boolean().optional(),
    b2bReceivablesAllowed: z.boolean().optional(),
    b2cReceivablesAllowed: z.boolean().optional(),
    concentrationLimitPercent: decimalField,
    minInvoiceSizeAmount: decimalField,
    maxInvoiceSizeAmount: decimalField,
    minInvoiceAgeDays: z.number().int().optional(),
    maxInvoiceDilutionPercent: decimalField,
    minDebtorCreditScore: z.number().int().optional(),
    customerCreditInsuranceRequired: z.boolean().optional(),
    existingLiensAccepted: z.boolean().optional(),
    taxLiensAccepted: z.boolean().optional(),
    uccFilingRequired: z.boolean().optional(),
    minEligibleArAmount: decimalField,
    maxArConcentrationPercent: decimalField,
    minMonthlyPayablesAmount: decimalField,
    vendorSupplierFinancingAllowed: z.boolean().optional(),
    tradePayablesFinancingAllowed: z.boolean().optional(),
    inventoryFinancingAllowed: z.boolean().optional(),
    supplyChainFinanceAllowed: z.boolean().optional(),
    domesticVendorsAllowed: z.boolean().optional(),
    internationalVendorsAllowed: z.boolean().optional(),
    governmentContractorsAllowed: z.boolean().optional(),
    maxVendorConcentrationPercent: decimalField,
    minVendorCreditQuality: z.string().optional(),
    vendorVerificationRequired: z.boolean().optional(),
    purchaseOrderRequired: z.boolean().optional(),
    minEligiblePayablesAmount: decimalField,
    maxPayablesConcentrationPercent: decimalField,
    domesticPosAllowed: z.boolean().optional(),
    governmentPosAllowed: z.boolean().optional(),
    recurringPosAllowed: z.boolean().optional(),
    oneTimePosAllowed: z.boolean().optional(),
    manufacturingRequired: z.boolean().optional(),
    finishedGoodsAllowed: z.boolean().optional(),
    rawMaterialsAllowed: z.boolean().optional(),
    supplierVendorPaymentAllowed: z.boolean().optional(),
    purchaseOrderAssignmentAllowed: z.boolean().optional(),
    minPoAmountAmount: decimalField,
    maxPoAmountAmount: decimalField,
    minCustomerCreditScore: z.number().int().min(0).optional(),
    minCustomerCreditRating: z.string().optional(),
    maxCustomerConcentrationPercent: decimalField,
    minGrossProfitMarginPercent: decimalField,
    minCustomerDepositPercent: decimalField,
    customerVerificationRequired: z.boolean().optional(),
    minEligiblePoValueAmount: decimalField,
    maxPoConcentrationPercent: decimalField,
    criteriaNotes: z.string().optional(),

    statesSupported: z.array(z.string()).optional(),

    documents: z
      .array(
        z
          .object({
            id: z.string().uuid().optional(),
            documentTypeId: z.string().uuid().optional(),
          })
          .passthrough(),
      )
      .optional(),

    isActive: z.boolean().optional(),
  })
  .passthrough();

module.exports = {
  businessTypeSchema,
  propertyTypeSchema,
  lenderProductPayloadSchema,
  loanProductEnum,
  decimalField,
  numberField,
};
