const { logAudit } = require("../../../services/logger/auditLogger");
const {
  syncLoiRequiredDocuments,
  extractStoredBrokerLoiDocumentNames,
} = require("../../../services/loi/syncLoiRequiredDocuments");
const {
  LENDER_LOI_STATUS,
  getCurrentLenderLoiVersion,
  markLenderLoiVersionSentToBroker,
  listLenderLoiVersions,
} = require("../../../services/loi/loiVersionService");

/**
 * @param {import("fastify").FastifyInstance} fastify
 */
async function sendLoiToBrokerRoute(fastify) {
  fastify.post(
    "/:applicationLenderId/send-loi-to-broker",
    {
      schema: {
        tags: ["Lender -> Loan Pipeline"],
        summary: "Send generated LOI / term sheet to the broker after review",
        params: {
          type: "object",
          required: ["applicationLenderId"],
          properties: {
            applicationLenderId: { type: "string" },
          },
        },
      },
    },
    async (req, reply) => {
      const prisma = fastify.prisma;

      try {
        if (
          !req.user ||
          req.user.orgType !== "LENDER" ||
          !req.user.organizationId
        ) {
          return reply.code(403).send({
            success: false,
            message: "Lender access only",
          });
        }

        const lenderOrgId = req.user.organizationId;
        const { applicationLenderId } = req.params;

        const lenderRecord = await prisma.applicationLender.findFirst({
          where: {
            id: applicationLenderId,
            lenderOrgId,
          },
          select: {
            id: true,
            loiUrl: true,
            loiTermsJson: true,
            loiSentToBrokerAt: true,
            lender: { select: { name: true } },
            loanApplication: {
              select: {
                id: true,
                applicationNumber: true,
                brokerOrgId: true,
              },
            },
          },
        });

        if (!lenderRecord) {
          return reply.code(404).send({
            success: false,
            message: "Application not found",
          });
        }

        if (!lenderRecord.loiUrl) {
          return reply.code(400).send({
            success: false,
            message: "Generate the LOI / term sheet before sending it to the broker",
          });
        }

        const currentVersion = await getCurrentLenderLoiVersion(
          prisma,
          applicationLenderId,
        );

        if (!currentVersion) {
          return reply.code(400).send({
            success: false,
            message: "LOI version not found. Generate the LOI first.",
          });
        }

        if (currentVersion.status === LENDER_LOI_STATUS.SENT_TO_BROKER) {
          return reply.code(400).send({
            success: false,
            message: "This LOI version was already sent to the broker",
            data: {
              loiSentToBrokerAt: currentVersion.sentToBrokerAt,
              versionNumber: currentVersion.versionNumber,
            },
          });
        }

        if (currentVersion.status !== LENDER_LOI_STATUS.DRAFT) {
          return reply.code(400).send({
            success: false,
            message: "Only a draft LOI can be sent to the broker",
          });
        }

        const brokerOrgId = lenderRecord.loanApplication.brokerOrgId;
        const lenderName = lenderRecord.lender?.name || "Lender";
        const sentAt = new Date();
        const requiredDocuments = extractStoredBrokerLoiDocumentNames(
          currentVersion.loiTermsJson || lenderRecord.loiTermsJson,
        );

        const [, notification] = await prisma.$transaction([
          prisma.applicationLender.update({
            where: { id: applicationLenderId },
            data: {
              loiUrl: currentVersion.loiUrl,
              loiTermsJson: currentVersion.loiTermsJson,
              loiSentToBrokerAt: sentAt,
              lastUpdatedAt: sentAt,
            },
          }),
          prisma.notification.create({
            data: {
              eventType: "LOI_GENERATED",
              category: "LOI",
              channel: "IN_APP",
              status: "QUEUED",
              recipientType: "BROKER",
              recipientOrgId: brokerOrgId,
              subject: "New LOI Received",
              body: `LOI generated by ${lenderName} for application ${lenderRecord.loanApplication.applicationNumber}`,
              metadata: {
                applicationId: lenderRecord.loanApplication.id,
                applicationNumber: lenderRecord.loanApplication.applicationNumber,
                applicationLenderId: lenderRecord.id,
                lenderName,
                loiPath: currentVersion.loiUrl,
                loiVersionNumber: currentVersion.versionNumber,
                loiVersionId: currentVersion.id,
              },
              sentAt,
            },
          }),
        ]);

        await markLenderLoiVersionSentToBroker(prisma, applicationLenderId);

        if (requiredDocuments.length > 0) {
          try {
            await syncLoiRequiredDocuments(prisma, {
              loanApplicationId: lenderRecord.loanApplication.id,
              applicationLenderId,
              documentNames: requiredDocuments,
              actor: "LENDER",
              orgId: lenderOrgId,
            });
          } catch (syncError) {
            fastify.log.error(
              syncError,
              "Failed to sync LOI required documents after sending to broker",
            );
          }
        }

        await logAudit({
          prisma,
          req,
          dashboard: "LENDER",
          category: "LOI",
          entityType: "ApplicationLender",
          entityId: applicationLenderId,
          action: "SEND_LOI_TO_BROKER",
          newValue: {
            loiUrl: currentVersion.loiUrl,
            loiSentToBrokerAt: sentAt,
            versionNumber: currentVersion.versionNumber,
            versionId: currentVersion.id,
          },
        });

        const versions = await listLenderLoiVersions(prisma, applicationLenderId);

        try {
          const {
            emitBrokerNotification,
          } = require("../../../services/notifications/notificationRealtime");
          emitBrokerNotification(fastify.io, brokerOrgId, notification);
        } catch (socketError) {
          fastify.log.warn("Socket emit failed:", socketError);
        }

        return reply.send({
          success: true,
          message: "LOI sent to broker successfully",
          data: {
            loiSentToBrokerAt: sentAt,
            loiUrl: currentVersion.loiUrl,
            versionNumber: currentVersion.versionNumber,
            versionId: currentVersion.id,
            versions,
          },
        });
      } catch (error) {
        fastify.log.error("Send LOI to broker failed:", error);

        return reply.code(500).send({
          success: false,
          message: error.message || "Failed to send LOI to broker",
        });
      }
    },
  );
}

module.exports = sendLoiToBrokerRoute;
