export const MAX_FIRST_NAME_LENGTH = 30;
export const MAX_LAST_NAME_LENGTH = 10;
export const MAX_COMPANY_NAME = 60;
export const MAX_COMPANY_ADDRESS_LENGTH = 60;
export const MAX_COMPANY_ADDRESS_CITY_LENGTH = 50;
export const MAX_COMPANY_ADDRESS_STATE_LENGTH = 15;
export const MAX_COMPANY_ADDRESS_ZIPCODE_LENGTH = 10;
export const MAX_COMPANY_ADDRESS_WEBSITE_LENGTH = 30;
export const MAX_LICENSE_NUMBER = 30;

export const MIN_FIRST_NAME_LENGTH = 1;
export const MIN_LAST_NAME_LENGTH = 1;

// Maximum 5 MB
export const MAX_FILE_SIZE = 5 * 1024 * 1024;